services:
  tiny:
    container_name: tiny
    build:
      dockerfile: Dockerfile
    restart: always
    links:
      - postgres
      - kafka
      - keydb
    depends_on:
      - postgres
      - kafka
      - keydb
    ports:
      - "8080:8080"

  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pkg/postgres/docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "5432:5432"

  keydb:
    image: eqalpha/keydb:x86_64_v6.0.18
    command: --requirepass password --notify-keyspace-events KEA
    volumes:
      - keydb_data:/keydb-data
    ports:
      - "6379:6379"

  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  clickhouse-server:
    image: yandex/clickhouse-server:20.1.2.4
    links:
      - kafka
    depends_on:
      - kafka
    volumes:
      - clickhouse_data:/var/lib/clickhouse
#      - pkg/clickhouse/dictionaries.xml:/etc/clickhouse-server/dictionaries.xml
#      - pkg/clickhouse/config.d/custom_config.xml:/etc/clickhouse-server/config.d/custom_config.xml
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
  clickhouse_data:
  postgres_data:
  keydb_data:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data: